INSERT INTO NOME_TABELA VALUES('1','Apicultura-Mel','1','354 - Apicultura','Colméia','Mel de abelhas','Kg','indeterminado','indeterminado','Kg de mel/colméia/ciclo','10','70','Própolis','0.1','Cera de Abelha','0','0','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','Unidades','Atenção, informar a quantidade por ano
',);INSERT INTO NOME_TABELA VALUES('2','Apicultura-Polen','1','354 - Apicultura','Colméia','Polen Apicola (IN NATURA)','Kg','indeterminado','indeterminado','Kg de polen/colméia/ciclo','10','30','Própolis','0.1','Cera de Abelha','0','0','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','Unidades','Atenção, informar a quantidade por ano
',);INSERT INTO NOME_TABELA VALUES('3','Avicultura-Codorna','2','826 - Avicultura - Codorna','mil aves','Ovos de codorna','cx. 30 unid.','indeterminado','indeterminado','caixas/mil aves/ciclo','5000','13000','Codorna descarte','105','0','0','0','','','0','','','','','','','','','','','','','','','','','1','(nr total de aves dividido por 1.000)','(quantidade total de ovos dividido por 30). Informar por ano.
',);INSERT INTO NOME_TABELA VALUES('4','Avicultura-Eng. Integração','3','826 - Avicultura','mil m2 aviário','Frango de granja integrado','Kg PV','engorda','integração','Kg PV de aves/mil m2/ciclo','20000','40000','Cama de aviário','15','','','','','','','','','','','','','','','','','','','','','','','6','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo, atentar p/ índice de mortalidade, densidade e peso final. Informar em Kg PV de frango total por ano
',);INSERT INTO NOME_TABELA VALUES('5','Avicultura-Eng.galeto.integ.','4','826 - Avicultura','mil m² aviário','Frango de granja galeto','Kg PV','engorda','integração','Kg PV de aves/mil m2/ciclo','20000','40000','Cama de aviário','15','','','','','','','','','','','','','','','','','','','','','','','9','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo, atentar p/ índice de mortalidade, densidade e peso final. Informar em Kg PV de frango galeto total por ano
',);INSERT INTO NOME_TABELA VALUES('6','Avicultura-Eng.Independ','5','826 - Avicultura','mil m2 aviário','Frango de granja','Kg PV','engorda','independente','Kg PV de aves/mil m2/ciclo','20000','40000','Cama de aviário','15','','','','','','','','','','','','','','','','','','','','','','','5.5','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo, atentar p/ índice de mortalidade, densidade e peso final. Informar em Kg PV de frango total por ano
',);INSERT INTO NOME_TABELA VALUES('7','Avicultura-Franga Postura Integ. ','6','826 - Avicultura','mil m2 aviário','Franga Matriz Postura Integ.','CB','Recria','integração','Franga Matriz/mil m2/ciclo','2000','10000','Cama de aviário','15','','','','','','','','','','','','','','','','','','','','','','','2','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo atentar p/ índice de mortalidade. Informar a quantidade de Frangas total por ano
',);INSERT INTO NOME_TABELA VALUES('8','Avicultura-Franga Matriz  Postura ','432','826 - Avicultura','mil m2 aviário','FRANGA MATRIZ POSTURA','CB','Recria','independente','Franga Matriz/mil m2/ciclo','24500','30600','Cama de aviário','10','','','','','','','','','','','','','','','','','','','','','','','2.2','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo atentar p/ índice de mortalidade. Informar a quantidade de Frangas total por ano
',);INSERT INTO NOME_TABELA VALUES('9','Avicultura-frango caipira','7','826 - Avicultura','mil aves','Frango caipira','Kg PV','engorda','independente','Kg PV de aves/mil aves/ciclo','1500','3000','0','0','0','0','0','0','','0','','','','','','','','','','','','','','','','','3.5','(nr total de aves em produção dividido por 1.000)','No cálculo, atentar p/ índice de mortalidade e peso final. Informar em Kg PV frango caipira total por ano
',);INSERT INTO NOME_TABELA VALUES('10','Avicultura-Frango/Macho Mat Post ','8','826 - Avicultura','mil m2 aviário','Frango/Macho Matriz Postura','CB','Recria','independente','Frango Macho/mil m2/ciclo','2000','10000','Cama de aviário','15','','','','','','','','','','','','','','','','','','','','','','','2','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo atentar p/ índice de mortalidade. Informar a quantidade de Frango/Macho Matriz Postura por ano.
',);INSERT INTO NOME_TABELA VALUES('11','Avicultura-peru-integrado','9','826 - Avicultura','mil m2 aviário','Peru para abate','Kg PV','Terminação','integração','Kg PV de aves/mil m2/ciclo','30000','65000','Cama de aviário','40','','','','','','','','','','','','','','','','','','','','','','','3','(soma das áreas dos aviários, em m², dividido por 1.000)','No cálculo, atentar p/ índice de mortalidade, densidade e peso final. Informar em Kg PV de peru total por ano
',);INSERT INTO NOME_TABELA VALUES('12','Avicultura-pinto 01 dia (corte)','10','826 - Avicultura','mil aves','Pinto de 1 dia granja (corte)','CB','indeterminado','independente','Pintos/mil aves/ciclo','10000.01','14000','Esterco de aviário','6.77','Galinha matriz (descarte)','1630.25','','','','','','','outros itens (justificar)','','','','','','','','','','','','','','1','Nr. total de aves (machos + fêmeas + jovens)','Quantidade de pintos de 01 dia. Informar por ano (01 ciclo = 01 ano)
',);INSERT INTO NOME_TABELA VALUES('13','Avicultura-Post-Ovos Fért Peru','11','826 - Avicultura','mil aves em postura','Ovos Férteis-Peru integr.','duzia','Recria/Postura','integração','Dúzias de ovos/mil aves/ciclo','8000','15000','Esterco de aviário','7','Galinha descarte','1200','0','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','(nr total de aves em produção dividido por 1.000)','(quantidade total de ovos dividido por 12). Informar por ano
',);INSERT INTO NOME_TABELA VALUES('14','Avicultura-Postura','11','826 - Avicultura','mil aves em postura','Ovo de granja','duzia','indeterminado','indeterminado','Dúzias de ovos/mil aves/ciclo','2000.01','28000','Esterco de aviário','7','Galinha descarte','1200','0','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','(nr total de aves em produção dividido por 1.000)','(quantidade total de ovos dividido por 12). Informar por ano
',);INSERT INTO NOME_TABELA VALUES('15','Avicultura-Postura-caipira','12','826 - Avicultura','mil aves em postura','Ovo caipira','duzia','indeterminado','indeterminado','Dúzias de ovos/mil aves/ciclo','17000','22000','Galinha descarte','1196','0','0','0','0','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','(nr total de aves em produção dividido por 1.000)','(quantidade total de ovos dividido por 12). Informar por ano
',);INSERT INTO NOME_TABELA VALUES('16','Avicultura-Postura-Ovos Férteis','12','826 - Avicultura','mil aves em postura','Ovos Férteis','duzia','indeterminado','indeterminado','Dúzias de ovos/mil aves/ciclo','8000','15000','Esterco de aviário','7','Galinha descarte','1200','0','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','(nr total de aves em produção dividido por 1.000)','(quantidade total de ovos dividido por 12). Informar por ano
',);INSERT INTO NOME_TABELA VALUES('17','Bovinocultura-Confinamento','13','825 - Bovinocultura','boi magro p/engorda','Boi gordo','Kg PV','engorda','confinamento','Ganho de peso(Kg)/cab/dia','0.8','1.7','0','0','0','0','0','','','0','','','','','','','','','91','100','351','375','','','1.3','1.5','1','Informar em nr. de cabeças','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de boi gordo total (=nr.bois gordos vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('18','Bovinocultura-Cr/Rec','13','825 - Bovinocultura','matriz bovina','Boi magro','Kg PV','Cria/recria','extensivo','bois magro/matriz/ano','0.25','0.45','Bezerra Zebuina','13','Novilha Zebuina','26','Vaca descarte','78','','0','','','outros itens (justificar)','','331','360','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices de natalidade e de mortalidade. Informar em Kg PV de boi magro total (=nr.bois magros vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('19','Bovinocultura-CR/Rec/Eng','14','825 - Bovinocultura','matriz bovina','Boi gordo','Kg PV','cria/recria/engorda','extensivo','bois gordo/matriz/ano','0.25','0.45','Bezerra Zebuina','13.5','Novilha zebuina','26.5','Vaca descarte','78','','0','','','outros itens (justificar)','','451','500','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices de natalidade e mortalidade. Informar em Kg PV de boi gordo total (=nr.bois gordos vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('20','Bovinocultura-Cria','14','825 - Bovinocultura','matriz bovina','Bezerro (corte)','Kg PV','cria','extensivo','bezerros/matriz/ano','0.25','0.45','Bezerra Zebuina','15','Novilha zebuina','30.5','Vaca descarte','78','','0','','','outros itens (justificar)','','150','175','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices de natalidade e de mortalidade. Informar em Kg PV de bezerro total (=nr.bezerros vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('21','Bovinocultura-embrião bovino','15','825 - Bovinocultura','matriz bovina','Embrião bovino','Un ','Reprodução-cria','semi-intensivo','Unidades/matriz/ano','2','14','Bezerro','64.28','vaca descarte','0','Tourinho Zebuino PO','','','0','','','outros itens (justificar)','','','','','','321','365','326','350','','','0.38','0.46','1','Informar em nr. de matrizes para produção do embrião','Quantidade de embriões produzidos. Informar por ano (01 ciclo = 01 ano)
',);INSERT INTO NOME_TABELA VALUES('22','Bovinocultura-eng-novilhas','15','825 - Bovinocultura','novilha para engorda','Novilha gorda','Kg PV','engorda','extensivo','Ganho de peso(Kg)/cab/dia','0.3','0.7','0','0','0','0','0','','','0','','','','','','','','','321','365','326','350','','','0.38','0.46','1','Informar em nr. de cabeças de novilhas p/ engorda','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de novilha gorda total (=nr.novilhas gordas vendidas x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('23','Bovinocultura-engorda','16','825 - Bovinocultura','boi magro p/engorda','Boi gordo','Kg PV','engorda','extensivo','Ganho de peso/cab/dia','0.3','0.7','0','0','0','0','0','','','0','','','','','','','','','321','365','326','350','','','','','1','Informar em nr. de cabeças','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de boi gordo total (=nr.bois gordos vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('24','Bovinocultura-engorda vacas','16','825 - Bovinocultura','vaca magra','Vaca gorda','Kg PV','engorda','extensivo','Ganho de peso(Kg)/cab/dia','0.3','0.7','0','0','0','0','0','','','0','','','','','','','','','321','365','326','350','','','0.38','0.46','1','Informar em nr. de cabeças de vacas magras','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de vaca gorda total (=nr.vacas gordas vendidas x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('25','Bovinocultura-Leite','17','825 - Bovinocultura','Matriz bovina','Leite','LITRO','indeterminado','extensivo','l/dia/matriz','2.01','40','Bezerro','64.28','vaca descarte','72','Bezerra','64','','0','','','outros itens (justificar)','','','','0.76','0.8','231','240','','','','','','','1','Informar tanto vacas em produção como vacas secas','No cálculo, atentar p/ índices de natalidade, pois somente vacas paridas produzem leite, e de duração da lactação.
',);INSERT INTO NOME_TABELA VALUES('26','Bovinocultura-Leite Tipo B','17','825 - Bovinocultura','matriz bovina','Leite tipo B','LITRO','indeterminado','intensivo','l/dia/matriz','16.01','50','vaca descarte','72','0','0','0','','','0','','','','','','','0.81','0.85','301','310','','','','','','','1','Informar tanto vacas em produção como vacas secas','No cálculo, atentar p/ índices de natalidade, pois somente vacas paridas produzem leite, e de duração da lactação.
',);INSERT INTO NOME_TABELA VALUES('27','Bovinocultura-Novilha PO','18','825 - Bovinocultura','Matriz bovina PO','Novilha Zebuina PO','Cabeça','cria/recria','semi-intensivo','Cab de Novilha PO/matriz/ano','0.11','0.3','Boi magro zebuino','79.2','Novilha zebuina','66','Vaca descarte','90','Tourinho Zebuino PO','0.22','','','outros itens (justificar)','','','','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices de natalidade, mortalidade e porcentagem de tourinhos classificados como PO
',);INSERT INTO NOME_TABELA VALUES('28','Bovinocultura-rec eng-novilhas','18','825 - Bovinocultura','bezerra p/ rec e engorda','Novilha gorda','Kg PV','engorda','extensivo','Ganho de peso(Kg)/cab/dia','0.25','0.7','0','0','0','0','0','','','0','','','','','','','','','321','365','326','350','','','0.38','0.46','1','Informar em nr. de cabeças de bezerras p/ recria-engorda','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de novilha gorda total (=nr.novilhas gordas vendidas x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('29','Bovinocultura-rec/eng','19','825 - Bovinocultura','bezerro p/ rec e engorda','Boi gordo','Kg PV','recria/engorda','extensivo','Ganho de peso(Kg)/cab/dia','0.25','0.65','0','0','0','0','0','','','0','','','','','','','','','701','725','151','170','','','0.33','0.41','1','Informar em nr. de cabeças','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de médio boi gordo total (=nr.bois gordos vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('30','Bovinocultura-Recria','19','825 - Bovinocultura','bezerro p/ recria','Boi magro','Kg PV','recria','extensivo','Ganho de peso(Kg)/cab/dia','0.25','0.65','0','0','0','0','0','','','0','','','','','','','','','321','365','171','190','','','','','1','Informar em nr. de cabeças','No cálculo, atentar p/ índice de mortalidade. Informar em Kg de PV de boi magro total (=nr.bois magros vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('31','Bovinocultura-Tourinho PO','20','825 - Bovinocultura','Matriz bovina PO','Tourinho Zebuino PO','Cabeça','cria/recria','semi-intensivo','Cab de tourinho PO/matriz/ano','0.11','0.2','Boi magro zebuino','79.2','Novilha zebuina','66','Vaca descarte','90','Novilha Zebuina PO','0.22','','','outros itens (justificar)','','','','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices de natalidade, mortalidade e porcentagem de tourinhos classificados como PO
',);INSERT INTO NOME_TABELA VALUES('32','Bubalinocultura-CR/Rec/Eng','20','1571 - Bubalinocultura','matriz bubalina','Búfalo gordo','Kg PV','cria/recria/engorda','extensivo','búfalos gordo/matriz bubalina/ano','0.25','0.45','búfala descarte','118.5','bezerro bubalino','26.5','Novilha Bubalina descarte','78','','0','','','outros itens (justificar)','','451','500','','','','','','','','','','','1','Informar tanto búfalas paridas como não paridas','No cálculo, atentar p/ índices de natalidade e mortalidade. Informar em Kg PV de búfalo gordo total (=nr.búfalos gordos vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('33','Bubalinocultura-leite','21','1571 - Bubalinocultura','matriz bubalina','Leite de búfala','LITRO','indeterminado','semi-intensivo','l/dia/matriz','2.01','12','Búfala descarte','118.5','Bezerro bubalino cruzado','59','0','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','Informar tanto búfalas em produção como búfalas secas','No cálculo, atentar p/ índices de natalidade e duração da lactação.
',);INSERT INTO NOME_TABELA VALUES('34','Caprinocultura-corte','21','827 - Caprinocultura','matriz caprina','Cabrito para abate','Kg PV','ciclo completo ','semi-intensivo','KgPV de cabrito/Matriz/ano','20.01','40','cabra para abate','11.52','','','','','','','','','','','','','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices como cria/matriz/ano, mortalidade, peso de abate. Informar em Kg PV de cabrito total
',);INSERT INTO NOME_TABELA VALUES('35','Caprinocultura-leite','22','827 - Caprinocultura','matriz caprina','leite de cabra','LITRO','indeterminado','semi-intensivo','l/dia/matriz','2.01','10','cabra para abate','37.6','Cabrito para abate','13.96','0','','','0','','','outros itens (justificar)','','','','1.36','1.4','171','180','','','','','','','1','Informar tanto cabras em produção como cabras secas','No cálculo, atentar p/ índices de fertilidade, nr de parições/cabra/ano, média do nr de crias/cabra/parto, duração da lactação.
',);INSERT INTO NOME_TABELA VALUES('36','Equideocultura','22','2241 - Equideocultura','matriz equina','Potra','Cabeça','indeterminado','indeterminado','Cabeça/Matriz','0.231','0.27','Potro','0.2','Equinos - Descarte','0.1','matriz equina','','','','','','','','','','','','','','','','','','','','1','','
',);INSERT INTO NOME_TABELA VALUES('37','Ovinocultura-Confinamento','22','828 - Ovinocultura','Cordeiro Desmamado','cordeiro para abate','Kg PV','engorda','confinamento','KgPV de cordeiro/Cordeiro desmamado','25.01','50','','9.5','0','0','0','','','0','','','','','','','','','','','','','','','','','1','Informar em nr. de cabeças de cordeiro desmamado p/ engorda','No cálculo, atentar p/ índice de mortalidade. Informar em Kg PV de cordeiro p/ abate total (=nr.cordeiros gordos vendidos x peso médio de venda)
',);INSERT INTO NOME_TABELA VALUES('38','Ovinocultura-corte','23','828 - Ovinocultura','matriz ovina','cordeiro para abate','Kg PV','indeterminado','semi-intensivo','KgPV de cordeiro/matriz/ano','12','75','ovelha para abate','9.5','0','0','0','','','0','','','outros itens (justificar)','','','','1.01','1.05','191','200','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices como cria/matriz/ano, mortalidade, peso de abate. Informar em Kg PV de cordeiro total
',);INSERT INTO NOME_TABELA VALUES('39','Ovinocultura-leite','23','828 - Ovinocultura','matriz ovina','Leite de ovelha in natura','LITRO','indeterminado','semi-intensivo','L/Dia/MATR OVINA','2.01','2.5','cordeiro para abate','35','','','','','','','','','','','','','','','','','','','','','','','','','
',);INSERT INTO NOME_TABELA VALUES('40','Ovinocultura-Matriz p/ Reprodução','23','828 - Ovinocultura','matriz ovina','Matriz Ovina p/ reprodução(Corte)','CB','indeterminado','semi-intensivo','Cabeça de Matriz Ovina/matriz/ano','0.15','0.5','ovelha para abate','9.5','Reprodutor Ovino (Corte)','0','Cordeiro p/ abate','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices como cria/matriz/ano e mortalidade. Informar cabeças de Matriz p/Reprodução (Corte) total.
',);INSERT INTO NOME_TABELA VALUES('41','Ovinocultura-Reprodutor Ovino','24','828 - Ovinocultura','matriz ovina','Reprodutor Ovino Corte','CB','indeterminado','semi-intensivo','Cabeça de Reprodutor Ovino/matriz/ano','0.1','0.4','ovelha para abate','9.5','Matriz Ovina p/ reprodução(Corte)','0','Cordeiro p/ abate','','','0','','','outros itens (justificar)','','','','','','','','','','','','','','1','Informar tanto matrizes paridas como não paridas','No cálculo, atentar p/ índices como cria/matriz/ano e mortalidade. Informar cabeças de Reprodutor Ovino (Corte) total.
',);INSERT INTO NOME_TABELA VALUES('42','Piscicultura-Alevino II-Pintado','24','433 - Piscicultura','M3 Tanque','Pintado (Alevino II)','Un ','cria/recria','indeterminado','Unidades/m3 tanque/ano','1200','4500','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','somatório dos volumes, em m³, de todos os tanques','Atenção, informar em unidades por ciclo/ano.
',);INSERT INTO NOME_TABELA VALUES('43','Piscicultura-Alevino II-Tilápia','25','433 - Piscicultura','HA LMDAGUA','Tilápia (Alevino II)','Mil cabeças','cria/recria','indeterminado','Mil alevinos/ha/ciclo','500','2500','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em unidades por ciclo/ano.
',);INSERT INTO NOME_TABELA VALUES('44','Piscicultura-Alevino I-Tambacu','25','433 - Piscicultura','HA LMDAGUA','Tambacu (Alevino I)','Mil cabeças','cria','indeterminado','Mil alevinos/ha/ciclo','400.01','1500','0','0','0','0','0','0','','','','','','','','','','','','','','','','','1','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em unidades por ciclo/ano.
',);INSERT INTO NOME_TABELA VALUES('45','Piscicultura-Alevino I-Tilápia','26','433 - Piscicultura','M3 Tanque','Tilápia (Alevino I)','Un ','cria','indeterminado','Unidades/m3 tanque/ano','100','700','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','somatório dos volumes, em m³, de todos os tanques','Atenção, informar em unidades por ciclo/ano.
',);INSERT INTO NOME_TABELA VALUES('46','Piscicultura-Carpa','26','433 - Piscicultura','HA LMDAGUA','Carpa','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','2000','16000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('47','Piscicultura-Catfish','27','433 - Piscicultura','HA LMDAGUA','Catfish','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','4000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('48','Piscicultura-Lambari vivo','152','433 - Piscicultura','HA LMDAGUA','Lambari vivo','KG','indeterminado','indeterminado','KG/HA LM','6250.01','7900','','','','','','','','','','','','','','','','','','','','','','','','','','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('49','Piscicultura-Matrinchan','27','433 - Piscicultura','HA LMDAGUA','Matrinchan','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','2000','16000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('50','Piscicultura-Pacu','28','433 - Piscicultura','HA LMDAGUA','Pacu','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','6000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('51','Piscicultura-Pacu-Tq.Rede','28','433 - Piscicultura','m3 de Tanque Rede','Pacu','Kg','engorda','indeterminado','Kg de pacu/m3 de TR/ciclo','30','230','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','2','somatório dos volumes, em m³, de todos os tanques-rede','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('52','Piscicultura-Piau-açu','29','433 - Piscicultura','HA LMDAGUA','Piau-açu','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','6000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('53','Piscicultura-Pintado','29','433 - Piscicultura','HA LMDAGUA','Pintado ','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','6000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('54','Piscicultura-Pintado-Tq.Rede','30','433 - Piscicultura','m3 de Tanque Rede','Pintado ','Kg','engorda','indeterminado','Kg de pintado/m3 de TR/ciclo','30','230','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','2','somatório dos volumes, em m³, de todos os tanques-rede','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('55','Piscicultura-Tambacu','30','433 - Piscicultura','HA LMDAGUA','Tambacu','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','6000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('56','Piscicultura-Tambaqui','31','433 - Piscicultura','HA LMDAGUA','Tambaqui','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','6000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('57','Piscicultura-Tilápia','31','433 - Piscicultura','HA LMDAGUA','Tilápia','Kg','engorda','indeterminado','Kg de peixe/ha/ciclo','6000','15000','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','1.5','soma das áreas dos viveiros utilizados para tal finalidade, em ha de lâmina d´água','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('58','Piscicultura-Tilápia-Tq.Rede','32','433 - Piscicultura','m3 de Tanque Rede','Tilápia','Kg','engorda','indeterminado','Kg de tilápia/m3 de TR/ciclo','30','230','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','2','somatório dos volumes, em m³, de todos os tanques-rede','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('59','Piscicultura-Truta-Tq.Rede','32','433 - Piscicultura','m³/Tanque','Truta','kg','engorda','indeterminado','kg/m³/Tanque','90','110','','','','','','','','','','','','','','','','','','','','','','','','','1.5','somatório dos volumes, em m³, de todos os tanques-rede','Atenção, informar em Kg PV produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('60','Piscicultura-Truta-Tq.Rede','32','433 - Piscicultura','m³/Tanque','Truta','kg','engorda','indeterminado','kg/m³/Tanque','60.01','75','','','','','','','','','','','','','','','','','','','','','','','','','','','
',);INSERT INTO NOME_TABELA VALUES('61','Sericicultura','32','459 - SERICICULTURA','Ha de Amoreira','Casulo Verde de Bicho da Seda','Kg','indeterminado','indeterminado','Kg de casulo/Ha de Amoreira','60','1000','0','','0','','0','','','','','','','','','','','','','','','','','','','','1','soma das áreas em Ha da lavoura de amoreira utilizados para tal finalidade.','Atenção, informar em Kg de Casulo Verde de Bicho da Seda produzido por ano.
',);INSERT INTO NOME_TABELA VALUES('62','suinocultura-completo','33','829 - Suinocultura','matriz suina','suino terminado','Kg PV','ciclo completo ','independente','suinos term./mat suina/ciclo','8','14','Matriz suina-descarte','77','0','0','0','','','0','','','','','96','100','','','','','','','','','','','2.3','Informar tanto matrizes paridas como não paridas','Atentar p/ índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de suíno terminado por ano(total suíno terminado no períodoxPeso médio)
',);INSERT INTO NOME_TABELA VALUES('63','suinocultura-completo integração','33','829 - Suinocultura','matriz suina','suino terminado (integrado)','Kg PV','ciclo completo ','integração','suinos term./mat suina/ciclo','8','14','0','77','0','0','0','','','0','','','','','96','100','','','','','','','','','','','2.3','Informar tanto matrizes paridas como não paridas','Atentar p/ índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de suíno terminado por ano(total suíno terminado no períodoxPeso médio)
',);INSERT INTO NOME_TABELA VALUES('64','Suinocultura-cria','34','829 - Suinocultura','matriz suina','leitão desmamado p/ creche','Kg PV','cria','independente','leitões desm./mat suina/ciclo','5','14','0','0','0','0','0','','','0','','','','','','','','','','','','','5.1','5.5','','','2.4','Informar tanto matrizes paridas como não paridas','Atentar p/índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de leitão total por ano(total de leitões desmamados no períodoxPeso médio )
',);INSERT INTO NOME_TABELA VALUES('65','Suinocultura-cria/creche','34','829 - Suinocultura','matriz suina','leitão p/rec/term (ind.)','Kg PV','cria/creche','independente','leitões/mat suina/ciclo','8','14','Matriz suina-descarte','32.08','0','0','0','','','0','','','','','','','','','','','','','','','','','2.4','Informar tanto matrizes paridas como não paridas','Atentar p/ índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de leitão por ano(total de leitões produzidos no período x Peso médio)
',);INSERT INTO NOME_TABELA VALUES('66','Suinocultura-cria/creche-integrado','35','829 - Suinocultura','matriz suina','leitão p/recria/term (int.)','Kg PV','cria/creche','integração','leitões/mat suina/ciclo','8','14','0','0','0','0','0','','','0','','','','','24','25','','','','','','','','','','','2.4','Informar tanto matrizes paridas como não paridas','Atentar p/ índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de leitão por ano(total de leitões produzidos no período x Peso médio)
',);INSERT INTO NOME_TABELA VALUES('67','Suinocultura-cria-integração','35','829 - Suinocultura','matriz suina','leitão desmamado (int.)','Kg PV','cria','integração','leitões desm./mat suina/ciclo','5','14','0','0','0','0','0','','','0','','','','','','','','','','','','','5.1','5.5','','','2.4','Informar tanto matrizes paridas como não paridas','Atentar p/índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de leitão total por ano(total de leitões desmamados produzidos no períodoxPeso médio)
',);INSERT INTO NOME_TABELA VALUES('68','suinocultura-Matriz Reprodução','36','829 - Suinocultura','matriz suina','Matriz Suína Reprodução','Kg PV','ciclo completo ','intensivo','matriz suina reprodução/mat suina/ciclo','4','10','Matriz suina-descarte','77','Leitão p/ recria/terminação','0','0','','','0','','','outros itens (justificar)','','96','100','','','','','','','','','','','2.3','Informar tanto matrizes paridas como não paridas','Atentar p/ índices:leitões nascidos/parto/porca e mortalidade.Informar KgPV de suíno terminado por ano(total suíno terminado produzido no períodoxPeso médio)
',);INSERT INTO NOME_TABELA VALUES('69','Suinocultura-rec/terminação','36','829 - Suinocultura','Leitão para recria/term','suíno terminado','Kg PV','recria/terminação','independente','Kg PV de terminado/cabeça/ciclo','86','130','0','0','0','0','0','','','0','','','','','','','','','','','','','','','','','3.75','Informar nr de cabeças de Leitão para recria/terminação','Atentar p/ índice de mortalidade. Informar em Kg PV de suino total /ano. (nr. total de suinos terminados no ano x Peso Médio)
',);INSERT INTO NOME_TABELA VALUES('70','Suinocultura-rec/term-integração','37','829 - Suinocultura','Leitão para recria/term','suino term. Integrado','Kg PV','recria/terminação','integração','Kg PV de terminado/cabeça/ciclo','86','130','0','','0','','0','','','','','','','','96','100','','','','','','','','','','','3.75','Informar nr de cabeças de Leitão para recria/terminação','Atentar p/ índice de mortalidade. Informar em Kg PV de suino total por ciclo. (=nr. total de suinos terminados no ano x Peso Médio)
',);